package postgres

const (
	RoleTable               = "public.roles"
	RuleItemTable           = "public.rule_item"
	RuleTable               = "public.rule"
	UsersTable              = "public.users"
	RealmTable              = "public.realms"
	AccessTable             = "public.accesses"
	SectionTable            = "public.sections"
	ColumnsTable            = "public.columns"
	CreatingFormTable       = "public.creating_form"
	InstrumentsTable        = "public.instruments"
	DocumentsTable          = "public.documents"
	VerificationDocsTable   = "public.verification_docs"
	VerificationTable       = "public.verifications"
	ContextTable            = "public.context_menu"
	ToolsMenuTable          = "public.tools_menu"
	CustomContextMenuTable  = "public.custom_context_menu"
	RepairTable             = "public.repair"
	VerificationFieldsTable = "public.verification_fields"
	PreservationTable       = "public.preservation"
	TransferToSaveTable     = "public.transfer_to_save"
	TransferToDepTable      = "public.transfer_to_department"
	WriteOffTable           = "public.write_off"
	HistoryTypesTable       = "public.history_types"
	FiltersTable            = "public.filters"
)
